In [1]:
import numpy as np
import logging
from tfidf import tf_idf

$\mathrm{tf}=f_{t,d}$

In [2]:
def tfmethod(term, document):
    """this is the binary """
    tf = 0
    for word in document:
        if word == term:
            tf += 1
    return tf / len(document)

$\mathrm{idf}_{(t,D)} = \log_{10}\frac{N+1}{\mathit{df}} $

In [3]:
def idfmethod(term,documents):
    N = len(documents)
    df = 0
    for document in documents:
        if term in document:
            df += 1
    idf = np.log10((N)/df)
#     logging.debug(f"np.log10(({N}+1)/{df})")
    return df,idf

In [4]:
t = tf_idf(tfmethod,idfmethod)

In [5]:
t.pretty_solve([["the","best","italian","restaurant","enjoy","the","best","pasta"],
                ["american","restaurant","enjoy","the","best","hamburger"],
                ["korean","restaurant","enjoy","the","best","bibimbab"],
                ["the","best","the","best","american","restaurant"]])

2019-09-25 23:17:49,888 [  DEBUG] document: [['the', 'best', 'italian', 'restaurant', 'enjoy', 'the', 'best', 'pasta'], ['american', 'restaurant', 'enjoy', 'the', 'best', 'hamburger'], ['korean', 'restaurant', 'enjoy', 'the', 'best', 'bibimbab'], ['the', 'best', 'the', 'best', 'american', 'restaurant']]
2019-09-25 23:17:49,889 [  DEBUG] unique_words: ['the', 'best', 'italian', 'restaurant', 'enjoy', 'pasta', 'american', 'hamburger', 'korean', 'bibimbab']
2019-09-25 23:17:49,891 [  DEBUG] [[0.25       0.25       0.125      0.125      0.125      0.125
  0.         0.         0.         0.        ]
 [0.16666667 0.16666667 0.         0.16666667 0.16666667 0.
  0.16666667 0.16666667 0.         0.        ]
 [0.16666667 0.16666667 0.         0.16666667 0.16666667 0.
  0.         0.         0.16666667 0.16666667]
 [0.33333333 0.33333333 0.         0.16666667 0.         0.
  0.16666667 0.         0.         0.        ]]
2019-09-25 23:17:49,896 [  DEBUG] tfidf: [[0.         0.         0.0752575 

(0, 0) 1.00000 = 0.01157 / (0.10757*0.10757)
(0, 1) 0.16764 = 0.00033 / (0.10757*0.01803)
(0, 2) 0.16764 = 0.00033 / (0.10757*0.01803)
(0, 3) 0.00000 = 0.00000 / (0.10757*0.00000)
(1, 0) 0.15804 = 0.00033 / (0.11410*0.01803)
(1, 1) 1.00000 = 0.01302 / (0.11410*0.11410)
(1, 2) 0.18249 = 0.00043 / (0.11410*0.02082)
(1, 3) 0.43970 = 0.00252 / (0.11410*0.05017)
(2, 0) 0.12573 = 0.00033 / (0.14343*0.01803)
(2, 1) 0.14518 = 0.00043 / (0.14343*0.02082)
(2, 2) 1.00000 = 0.02057 / (0.14343*0.14343)
(2, 3) 0.00000 = 0.00000 / (0.14343*0.00000)
(3, 0) 0.00000 = 0.00000 / (0.05017*0.00000)
(3, 1) 1.00000 = 0.00252 / (0.05017*0.05017)
(3, 2) 0.00000 = 0.00000 / (0.05017*0.00000)
(3, 3) 1.00000 = 0.00252 / (0.05017*0.05017)


In [6]:
t.unique_words

['the',
 'best',
 'italian',
 'restaurant',
 'enjoy',
 'pasta',
 'american',
 'hamburger',
 'korean',
 'bibimbab']

In [7]:
t.idf_vector

array([[0.        , 0.        , 0.60205999, 0.        , 0.12493874,
        0.60205999, 0.30103   , 0.60205999, 0.60205999, 0.60205999]])

In [8]:
t.tf_vector

array([[0.25      , 0.25      , 0.125     , 0.125     , 0.125     ,
        0.125     , 0.        , 0.        , 0.        , 0.        ],
       [0.16666667, 0.16666667, 0.        , 0.16666667, 0.16666667,
        0.        , 0.16666667, 0.16666667, 0.        , 0.        ],
       [0.16666667, 0.16666667, 0.        , 0.16666667, 0.16666667,
        0.        , 0.        , 0.        , 0.16666667, 0.16666667],
       [0.33333333, 0.33333333, 0.        , 0.16666667, 0.        ,
        0.        , 0.16666667, 0.        , 0.        , 0.        ]])

In [9]:
t.df_vector

array([[4., 4., 1., 4., 3., 1., 2., 1., 1., 1.]])

In [10]:
t.tfidf_vector

array([[0.        , 0.        , 0.0752575 , 0.        , 0.01561734,
        0.0752575 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.02082312,
        0.        , 0.05017167, 0.10034333, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.02082312,
        0.        , 0.        , 0.        , 0.10034333, 0.10034333],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.05017167, 0.        , 0.        , 0.        ]])

In [11]:
t.calculate_cosine()

(0, 0) 1.00000 = 0.01157 / (0.10757*0.10757)
(0, 1) 0.16764 = 0.00033 / (0.10757*0.01803)
(0, 2) 0.16764 = 0.00033 / (0.10757*0.01803)
(0, 3) 0.00000 = 0.00000 / (0.10757*0.00000)
(1, 0) 0.15804 = 0.00033 / (0.11410*0.01803)
(1, 1) 1.00000 = 0.01302 / (0.11410*0.11410)
(1, 2) 0.18249 = 0.00043 / (0.11410*0.02082)
(1, 3) 0.43970 = 0.00252 / (0.11410*0.05017)
(2, 0) 0.12573 = 0.00033 / (0.14343*0.01803)
(2, 1) 0.14518 = 0.00043 / (0.14343*0.02082)
(2, 2) 1.00000 = 0.02057 / (0.14343*0.14343)
(2, 3) 0.00000 = 0.00000 / (0.14343*0.00000)
(3, 0) 0.00000 = 0.00000 / (0.05017*0.00000)
(3, 1) 1.00000 = 0.00252 / (0.05017*0.05017)
(3, 2) 0.00000 = 0.00000 / (0.05017*0.00000)
(3, 3) 1.00000 = 0.00252 / (0.05017*0.05017)


array([[1.        , 0.16764311, 0.16764311, 0.        ],
       [0.15804398, 1.        , 0.18249347, 0.43970357],
       [0.12573234, 0.1451832 , 1.        , 0.        ],
       [0.        , 1.        , 0.        , 1.        ]])