In [1]:
import numpy as np
import logging
from tfidf import tf_idf

$\mathrm{tf}=f_{t,d}$

In [2]:
def tfmethod(term, document):
    """this is the binary """
    tf = 0
    for word in document:
        if word == term:
            tf += 1
    return tf

$\mathrm{idf}_{(t,D)} = \log_{10}\frac{N+1}{\mathit{df}} $

In [3]:
def idfmethod(term,documents):
    N = len(documents)
    df = 0
    for document in documents:
        if term in document:
            df += 1
    idf = np.log10((N+1)/df)
#     logging.debug(f"np.log10(({N}+1)/{df})")
    return df,1

In [4]:
t = tf_idf(tfmethod,idfmethod)

In [5]:
t.pretty_solve([["hello","world","this","is","fun","hello"],["hulu","world","this","aww","lucu"]])

2019-09-25 21:13:26,732 [  DEBUG] document: [['hello', 'world', 'this', 'is', 'fun', 'hello'], ['hulu', 'world', 'this', 'aww', 'lucu']]
2019-09-25 21:13:26,734 [  DEBUG] unique_words: ['hello', 'world', 'this', 'is', 'fun', 'hulu', 'aww', 'lucu']
2019-09-25 21:13:26,736 [  DEBUG] [[2. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1.]]
2019-09-25 21:13:26,738 [  DEBUG] tfidf: [[2. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1.]]


In [6]:
t.idf_vector

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
t.tf_vector

array([[2., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 1., 1., 1.]])

In [8]:
t.df_vector

array([[1., 2., 2., 1., 1., 1., 1., 1.]])

In [9]:
t.tfidf_vector

array([[2., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 1., 1., 1.]])

In [10]:
t.calculate_cosine()

array([[1.        , 0.27216553],
       [0.27216553, 1.        ]])

In [14]:
np.dot(t.tfidf_vector,t.tfidf_vector.T)

array([[8., 2.],
       [2., 5.]])